### ISSUE TITLE
Suggestion: Take advantage of map rotation

### ISSUE THREAD

**Issue by ChristopherKing42** [mrgriscom/merc-extreme#29]
Some maps (such as Google maps) can be rotated. When rotated, the labels do not rotate (or another way to look at it is that the labels are rotating). I suggest using these to keep the labels from getting flipped when you do the projection.

**Comment by mrgriscom** [comment]
Thanks for the suggestion but it would add quite a bit of complication for the map tiles to know the orientation in which they're displayed in order to load the set with the correctly rotated labels. And it would also require a lot more bandwidth to re-load the tiles as the orientation changes and push the updated textures through to the GPU.
